import React from "react";
export const apartments = [
  {label: "All", value: "all"},
  {label: "Apartment", value: "apartment"},
  {label: "Studio", value: "studio"},
  {label: "Condo", value: "condo"},
  {label: "House", value: "house"},
  {label: "Cabin", value: "cabin"},
  {label: "Loft", value: "loft"},
  {label: "Room", value: "room"},
  {label: "Other", value: "other"},
];

export const amenities = [
  {label: "Wifi", value:"Wifi"},
  {label: "Full Kitchen", value:"full kitchen"},
  {label: "Washer & Dryer", value:"Washer & Dryer"},
  {label: "Free Parking", value:"Free Parking"},
  {label: "Hot Tub", value:"Hot Tub"},
  {label: "24/7 Security", value:"24/7 Security"},
  {label: "Wheel Chair Accessible", value:"Wheel Chair Accessible"},
  {label: "Elevator Access", value:"Elevator Access"},
  {label: "Dishwasher", value:"Dishwasher"},
  {label: "High-Speed Internet", value:"High-Speed Internet"},
  {label: "Air Conditioning", value:"Air Conditioning"},
  {label: "Smart TV", value:"Smart TV"},
  {label: "Outdoor Grill/BBQ", value:"Outdoor Grill/BBQ"},
  {label: "Coffee Maker", value:"Coffee Maker"},
  {label: "Swimming Pool", value:"Swimming Pool"},
  {label: "Balcony/Patio", value:"Balcony/Patio"},
  {label: "Beach Access", value:"Beach Access"},
  {label: "Gym/Fitness Centre", value:"Gym/Fitness Centre"},
  {label: "Fireplace", value:"Fireplace"},
  {label: "Mountain View", value:"Mountain View"},
  {label: "Hiking Trail Access", value:"Hiking Trail Access"},
  {label: "Pet-Friendly", value:"Pet-Friendly"},
  {label: "Ski Equipment Storage", value:"Ski Equipment Storage"},
  {label: "Extra Beds", value:"Extra Beds"},
  {label: "Smoke/Fire Alarm System", value:"Smoke/Fire Alarm System"},
]